1.2.1 Пример. Создать массив 5x2. Создать массив 5x2. Вывести все значения массива, значение элемента с индексом (3,1) и второй столбец. Индексация начинается с нуля.

In [2]:
import numpy as np
x = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10]])
print(x)
print(x[3][1])
print(x[1])

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
8
[3 4]


1.2.2 Пример. Выполнить следующее:
1. Создать вектор (одномерный массив) размера 10, заполненный нулями.
2. Создать вектор размера 10, заполненный единицами.
3. Создать вектор размера 10, заполненный заданным числом.
4. Создать вектор со значениями от 10 до 19.

In [3]:
a = np.zeros(10)
b = np.ones(10)
c = np.full(10, 5)
d = np.arange(10, 20)
print(a, "\n", b, "\n", c, "\n", d)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] 
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.] 
 [5 5 5 5 5 5 5 5 5 5] 
 [10 11 12 13 14 15 16 17 18 19]


1.2.3 Пример. Создать массив 10x10 со случайными значениями, найти минимум максимум и среднее значение.

In [4]:
Z = np.random.random((10, 10))
Zmin, Zmax, Zmean = Z.min(), Z.max(), Z.mean()
print(Zmin, Zmax, Zmean)

0.0046943659643157165 0.9984378911183184 0.44467825665049654


1.2.4 Пример. Задать матрицу размерности 5 на 5 и поменять 2 строки в матрице местами.

In [5]:
A = np.arange(25).reshape(5, 5)
A[[0, 1]] = A[[1, 0]]
print(A)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


1.2.5 Пример. Выяснить результат следующих выражений:

0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
0.3 == 3 * 0.1

In [6]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(0.3 == 3 * 0.1)

nan
False
False
nan
False


1.2.6 Пример. Отсортировать массив.

In [7]:
arr = np.array([8, 2, 7, 5, 4, 6, 3, 1])
print(np.sort(arr))

[1 2 3 4 5 6 7 8]


1.3.1 Задание. Создать 8x8 матрицу и заполнить её в шахматном порядке нулями и единицами.


In [16]:
arr = np.zeros(64).reshape(8,8)
for i in range(64):
  arr[i//8][(i+i//8)%8] = 1 if i % 2==0 else 0
print(arr)

[[1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]]


1.3.2 Задание. Создать 5x5 матрицу со значениями в строках от 0 до 4. Для создания необходимо использовать функцию arrange.

In [18]:
arr = np.array([np.arange(0, 5)] * 5)
print(arr)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


1.3.3 Задание. Создать массив 3x3x3 со случайными значениями.

In [19]:
arr = np.random.random((3,3,3))
print(arr)

[[[0.39993574 0.6590498  0.29023825]
  [0.42727099 0.40165729 0.27682751]
  [0.11930798 0.73722442 0.17863941]]

 [[0.19397212 0.41095744 0.13418152]
  [0.96916242 0.49238239 0.58784556]
  [0.58649718 0.49647881 0.94970769]]

 [[0.86193619 0.93373251 0.2168305 ]
  [0.35412918 0.43883582 0.43589335]
  [0.24818081 0.90030864 0.57302892]]]


1.3.4 Задание. Создать матрицу с 0 внутри, и 1 на границах.

In [14]:
arr = np.ones((9,9))
arr[1:-1, 1:-1] = 0
print(arr)

[[1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]]


1.3.5 Задание. Создайте массив и отсортируйте его по убыванию.

In [21]:
arr = np.random.random((3,3))
print(np.sort(arr)[::-1])

[[0.12179364 0.25098564 0.66160404]
 [0.10648238 0.10794422 0.81434701]
 [0.42402191 0.73149322 0.90477649]]


1.3.6 Задание. Создайте матрицу, выведите ее форму, размер и размерность.

In [22]:
arr = np.random.random((2,4,6))
print(f'Форма: {arr.shape}, размер: {np.size(arr) * arr.itemsize} байт, {np.size(arr)} элементов')

Форма: (2, 4, 6), размер: 384 байт, 48 элементов


2.2.1 Пример. Создать Series из списка Python, словаря Python, и массива Numpy (установить буквенные метки для последнего).

In [7]:
import numpy as np
import pandas as pd
lst = [1, 2, 3, 4, 5]
d = {'a':1, 'b':2, 'c':3}
ndarr = np.array([1, 2, 3, 4, 5])

s1 = pd.Series(lst)
s2 = pd.Series(d)
s3 = pd.Series(ndarr, ['a', 'b', 'c', 'd', 'e'])

print(s1)
print(s2)
print(s3)

0    1
1    2
2    3
3    4
4    5
dtype: int64
a    1
b    2
c    3
dtype: int64
a    1
b    2
c    3
d    4
e    5
dtype: int32


2.2.2 Пример. Дано два Series. Напечатать их первые элементы и все элементы после третьего (во втором фрейме).

In [8]:
s1 = pd.Series([1, 2, 3, 4, 5], ['a', 'b', 'c', 'd', 'e'])
s2 = pd.Series([5, 4, 3, 2, 1])
print(s1['a'])
print(s2[0])
print(s2[3:])

1
5
3    2
4    1
dtype: int64


2.2.3 Пример. СОздайте новый фрейм данных.

In [10]:
dataframe = pd.DataFrame()
dataframe['Имя'] = ['Джеки Джексон', 'Стивен Стивенсон']
dataframe['Возраст'] = [38, 25]
dataframe['Водитель'] = [True, False]
dataframe

Имя  Возраст  Водитель
0     Джеки Джексон       38      True
1  Стивен Стивенсон       25     False

2.2.4 Пример. Загрузите фрейм данных по ссылке: https://raw.githubusercontent.com/chrisalbon/simulated_datasets/master/titanic.csv

In [11]:
url = 'https://raw.githubusercontent.com/chrisalbon/simulated_datasets/master/titanic.csv'
dataframe = pd.read_csv(url)
dataframe.head(5)

Name PClass    Age     Sex  \
0                   Allen, Miss Elisabeth Walton    1st  29.00  female   
1                    Allison, Miss Helen Loraine    1st   2.00  female   
2            Allison, Mr Hudson Joshua Creighton    1st  30.00    male   
3  Allison, Mrs Hudson JC (Bessie Waldo Daniels)    1st  25.00  female   
4                  Allison, Master Hudson Trevor    1st   0.92    male   

   Survived  SexCode  
0         1        1  
1         0        1  
2         0        0  
3         0        1  
4         1        0

2.2.5 Пример. Пронализировать характеристики фрейма данных.

In [21]:
dataframe.head(2)

Name PClass   Age     Sex  Survived  SexCode
0  Allen, Miss Elisabeth Walton    1st  29.0  female         1        1
1   Allison, Miss Helen Loraine    1st   2.0  female         0        1

In [22]:
dataframe.tail(3)

Name PClass   Age   Sex  Survived  SexCode
1310  Zenni, Mr Philip    3rd  22.0  male         0        0
1311  Lievens, Mr Rene    3rd  24.0  male         0        0
1312    Zimmerman, Leo    3rd  29.0  male         0        0

In [23]:
dataframe.shape

(1313, 6)

In [24]:
dataframe.describe()

Age     Survived      SexCode
count  756.000000  1313.000000  1313.000000
mean    30.397989     0.342727     0.351866
std     14.259049     0.474802     0.477734
min      0.170000     0.000000     0.000000
25%     21.000000     0.000000     0.000000
50%     28.000000     0.000000     0.000000
75%     39.000000     1.000000     1.000000
max     71.000000     1.000000     1.000000

2.2.6 Пример. Выберите индивидуальные данные или срезы фрейма данных. 

In [25]:
dataframe.iloc[1:4]

Name PClass   Age     Sex  \
1                    Allison, Miss Helen Loraine    1st   2.0  female   
2            Allison, Mr Hudson Joshua Creighton    1st  30.0    male   
3  Allison, Mrs Hudson JC (Bessie Waldo Daniels)    1st  25.0  female   

   Survived  SexCode  
1         0        1  
2         0        0  
3         0        1

2.2.7 Пример. Требуется отобрать строки фрейма данных на основе некоторого условия. Необходимо сформировать новый фрейм данных из пассажиров первого класса.

In [28]:
dataframe[dataframe['PClass'] == '1st'].head(2)

Name PClass   Age     Sex  Survived  SexCode
0  Allen, Miss Elisabeth Walton    1st  29.0  female         1        1
1   Allison, Miss Helen Loraine    1st   2.0  female         0        1

2.3.1 Задание. Найдите евклидово расстояние между двумя Series (точками) a и b, не используя встроенную формулу.

In [15]:
a = pd.Series([5,3,7])
b=pd.Series([4,8,9])
dist = np.sqrt(sum((a-b)**2))
print(dist)

5.477225575051661


2.3.2 Задание. Найдите в Интернете ссылку на любой csv файл и сформируйте из него фрейм данных (например, коллекцию фреймов данных можно найти здесь: https://github.com/akmand/datasets).

In [2]:
import pandas as pd
url = 'https://raw.githubusercontent.com/akmand/datasets/main/helena.csv'
dataframe = pd.read_csv(url)
dataframe.head(5)

V1        V2        V3        V4        V5        V6        V7  \
0  0.005521  0.080556  0.110417  0.490822  0.586406  0.066414  0.092206   
1  0.049398  0.147917  0.541667  0.542865  0.515608  0.105128  0.475550   
2  0.548663  1.000000  1.000000  0.397029  0.627398  1.023440  1.004220   
3  0.023073  0.206250  0.238889  0.622998  0.764067  0.202599  0.177892   
4  0.224427  0.433333  0.902083  0.814199  0.576879  0.344413  0.822975   

         V8        V9       V10  ...      V19       V20        V21       V22  \
0  0.116352  0.379310  216.2600  ...  78.6894  17.23780  21.504200  14.43730   
1  0.049555  0.383460   90.2660  ...  59.7879   5.39341   3.819610  11.49240   
2  0.027381  0.451337   63.1644  ...  58.1429  -3.36598  -0.037489  10.63470   
3  0.071232  0.531712   57.3070  ...  55.4798  -1.05109  -4.755360  13.36710   
4  0.026121  0.425875  113.5670  ...  76.8475 -19.37170  32.270700   9.41442   

        V23      V24       V25       V26       V27  class  
0  17.37800  9.61674 -0.609370  1.044830  1.481790     41  
1   3.92947  5.91423  1.409210  4.749540  1.103820     92  
2   2.66018  3.93377 -0.898220  2.137790  1.054470     24  
3   2.85206  9.65162  0.224397 -0.220216 -0.273287     29  
4   4.34345  8.67710 -1.587580  1.117870 -0.545338     91  

[5 rows x 28 columns]

2.3.3 Заданине. Проделайте с получившемся из предыдущего задания фреймом данных те же действия, что и в примерах 2.2.5-2.2.7.

In [3]:
print('Head')
print(dataframe.head(2), end = '\n\n\n')
print('Tail')
print(dataframe.tail(3),end = '\n\n\n')
print('Shape')
print(dataframe.shape,end = '\n\n\n')
print('Describe')
print(dataframe.describe(),end = '\n\n\n')
print('Iloc')
print(dataframe.iloc[1:4],end = '\n\n\n')
print('>0.1 head')
print(dataframe[dataframe['V1'] > 0.1].head(2),end = '\n\n\n')

Head
         V1        V2        V3        V4        V5        V6        V7  \
0  0.005521  0.080556  0.110417  0.490822  0.586406  0.066414  0.092206   
1  0.049398  0.147917  0.541667  0.542865  0.515608  0.105128  0.475550   

         V8       V9      V10  ...      V19       V20       V21      V22  \
0  0.116352  0.37931  216.260  ...  78.6894  17.23780  21.50420  14.4373   
1  0.049555  0.38346   90.266  ...  59.7879   5.39341   3.81961  11.4924   

        V23      V24      V25      V26      V27  class  
0  17.37800  9.61674 -0.60937  1.04483  1.48179     41  
1   3.92947  5.91423  1.40921  4.74954  1.10382     92  

[2 rows x 28 columns]


Tail
             V1        V2        V3        V4        V5        V6        V7  \
65193  0.999352  1.000000  1.000000  0.501360  0.501075  0.999384  0.999414   
65194  0.206175  0.383333  0.944444  0.749915  0.550936  0.292477  0.830921   
65195  0.003096  0.102083  0.066667  0.844969  0.054704  0.091855  0.052645   

             V8       

3.2.1 Пример. Прошкалируйте числовой признак в диапазон между двумя значениями.

In [6]:
import numpy as np
from sklearn import preprocessing as prep

feature = np.array([[-500.5], [-100.1], [0], [100.1], [900.9]])
minmax_scale = prep.MinMaxScaler(feature_range = (0, 1))
scaled_feature = minmax_scale. fit_transform(feature)

scaled_feature

array([[0.        ],
       [0.28571429],
       [0.35714286],
       [0.42857143],
       [1.        ]])

3.2.2 Пример. Преобразуйте признак, чтобы он имел среднее значение 0 и стандартное отклонение 1.

In [10]:
x = np.array([[-1000.1], [-200.2], [500.5], [600.6], [9000.9]])
scaler = prep.StandardScaler()
standardized = scaler.fit_transform(x)
standardized

print('Среднее: ', round(standardized.mean()))
print('Стандартное отклонение: ', standardized.std())

Среднее:  0
Стандартное отклонение:  1.0


3.2.3 Пример. Дан фрейм данных
dfTest = pd.DataFrame({'A':[14.00,90.20,90.95,96.27,91.21],
 'B':[103.02,107.26,110.35,114.23,114.68],
 'C':['big','small','big','small','small']})
Необходимо масштабировать его числовые столбцы.

In [11]:
import pandas as pd
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
dfTest = pd.DataFrame({'A':[14.00, 90.20, 90.95, 96.27, 91.21],
                       'B': [103.02, 107.26, 110.35, 114.23, 114.68],
                       'C': ['big', 'small', 'big', 'small', 'small']})
dfTest[['A', 'B']] = scaler.fit_transform(dfTest[['A', 'B']])
dfTest

A         B      C
0  0.000000  0.000000    big
1  0.926219  0.363636  small
2  0.935335  0.628645    big
3  1.000000  0.961407  small
4  0.938495  1.000000  small

3.3.2 Задание. Загрузить фрейм данных по ссылке: https://raw.githubusercontent.com/akmand/datasets/master/iris.csv. Необходимо выполнить нормализацию первого числового признака (sepal_length_cm) с использованием минимаксного преобразования, а второго (sepal_width_cm) с задействованием z-масштабирования.

In [1]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import MinMaxScaler, StandardScaler
url = 'https://raw.githubusercontent.com/akmand/datasets/master/iris.csv'
dataframe = pd.read_csv(url)
mmscaler = MinMaxScaler(feature_range = (0, 1))
scaler = StandardScaler()

dataframe[['sepal_length_cm']] = mmscaler.fit_transform(dataframe[['sepal_length_cm']])
dataframe[['sepal_width_cm']] = scaler.fit_transform(dataframe[['sepal_width_cm']])
dataframe
#x = np.array(dataframe.sepal_length_cm), np.array(dataframe.sepal_width_cm)
#x = mmscaler.fit_transform(x[0].reshape(-1, 1)).reshape(1, -1), scaler.fit_transform(x[1].reshape(-1, 1)).reshape(1, -1)
#print(f'Sepal_length_cm: \n{x[0]} \n\n\n\n Sepal_width_cm: \n{x[1]}')

sepal_length_cm  sepal_width_cm  petal_length_cm  petal_width_cm  \
0           0.222222        1.032057              1.4             0.2   
1           0.166667       -0.124958              1.4             0.2   
2           0.111111        0.337848              1.3             0.2   
3           0.083333        0.106445              1.5             0.2   
4           0.194444        1.263460              1.4             0.2   
..               ...             ...              ...             ...   
145         0.666667       -0.124958              5.2             2.3   
146         0.555556       -1.281972              5.0             1.9   
147         0.611111       -0.124958              5.2             2.0   
148         0.527778        0.800654              5.4             2.3   
149         0.444444       -0.124958              5.1             1.8   

       species  
0       setosa  
1       setosa  
2       setosa  
3       setosa  
4       setosa  
..         ...  
145  virginica  
146  virginica  
147  virginica  
148  virginica  
149  virginica  

[150 rows x 5 columns]