1.2.1 Пример. Создать массив 5x2. Создать массив 5x2. Вывести все значения массива, значение элемента с индексом (3,1) и второй столбец. Индексация начинается с нуля.

In [2]:
import numpy as np
x = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10]])
print(x)
print(x[3][1])
print(x[1])

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
8
[3 4]


1.2.2 Пример. Выполнить следующее:
1. Создать вектор (одномерный массив) размера 10, заполненный
нулями.
2. Создать вектор размера 10, заполненный единицами.
3. Создать вектор размера 10, заполненный заданным числом.
4. Создать вектор со значениями от 10 до 19.

In [3]:
a = np.zeros(10)
b = np.ones(10)
c = np.full(10, 5)
d = np.arange(10, 20)
print(a, "\n", b, "\n", c, "\n", d)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] 
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.] 
 [5 5 5 5 5 5 5 5 5 5] 
 [10 11 12 13 14 15 16 17 18 19]


1.2.3 Пример. Создать массив 10x10 со случайными значениями, найти минимум максимум и среднее значение.

In [4]:
Z = np.random.random((10, 10))
Zmin, Zmax, Zmean = Z.min(), Z.max(), Z.mean()
print(Zmin, Zmax, Zmean)

0.0046943659643157165 0.9984378911183184 0.44467825665049654


1.2.4 Пример. Задать матрицу размерности 5 на 5 и поменять 2 строки в матрице местами.

In [5]:
A = np.arange(25).reshape(5, 5)
A[[0, 1]] = A[[1, 0]]
print(A)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


1.2.5 Пример. Выяснить результат следующих выражений:
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
0.3 == 3 * 0.1

In [6]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(0.3 == 3 * 0.1)

nan
False
False
nan
False


1.2.6 Пример. Отсортировать массив.

In [7]:
arr = np.array([8, 2, 7, 5, 4, 6, 3, 1])
print(np.sort(arr))

[1 2 3 4 5 6 7 8]


1.3.1 Задание. Создать 8x8 матрицу и заполнить её в шахматном порядке нулями и единицами.


In [16]:
arr = np.zeros(64).reshape(8,8)
for i in range(64):
  arr[i//8][(i+i//8)%8] = 1 if i % 2==0 else 0
print(arr)

[[1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]]


1.3.2 Задание. Создать 5x5 матрицу со значениями в строках от 0 до 4. Для создания необходимо использовать функцию arrange.

In [18]:
arr = np.array([np.arange(0, 5)] * 5)
print(arr)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


1.3.3 Задание. Создать массив 3x3x3 со случайными значениями.

In [19]:
arr = np.random.random((3,3,3))
print(arr)

[[[0.39993574 0.6590498  0.29023825]
  [0.42727099 0.40165729 0.27682751]
  [0.11930798 0.73722442 0.17863941]]

 [[0.19397212 0.41095744 0.13418152]
  [0.96916242 0.49238239 0.58784556]
  [0.58649718 0.49647881 0.94970769]]

 [[0.86193619 0.93373251 0.2168305 ]
  [0.35412918 0.43883582 0.43589335]
  [0.24818081 0.90030864 0.57302892]]]


1.3.4 Задание. Создать матрицу с 0 внутри, и 1 на границах.

In [20]:
arr = np.ones(9).reshape(3, 3)
arr[1, 1] = 0
print(arr)

[[1. 1. 1.]
 [1. 0. 1.]
 [1. 1. 1.]]


1.3.5 Задание. Создайте массив и отсортируйте его по убыванию.

In [21]:
arr = np.random.random((3,3))
print(np.sort(arr)[::-1])

[[0.12179364 0.25098564 0.66160404]
 [0.10648238 0.10794422 0.81434701]
 [0.42402191 0.73149322 0.90477649]]


1.3.6 Задание. Создайте матрицу, выведите ее форму, размер и размерность.

In [22]:
arr = np.random.random((2,4,6))
print(f'Форма: {arr.shape}, размер: {np.size(arr) * arr.itemsize} байт, {np.size(arr)} элементов')

Форма: (2, 4, 6), размер: 384 байт, 48 элементов
